services:
  odoo:
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE:-false}"
      - "traefik.docker.network=proxy"

      # HTTPS Router:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${VIRTUAL_HOST:-}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=le"

      # Service Port:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8069"

      # (Optional) zusätzliche redirect-Middleware wäre nicht nötig, da Traefik selbst 80->443 leitet.
